name: Rune Unit-Tests
on:
  push:
    branches:
      - main
      - Dev
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.9
      - name: Install dependencies
        run: |
          sudo apt-get install freeglut3
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Setup package
        run: python setup.py develop
      - name: Run tests with PyTest
        run: pytest tests/unitTests
